-- Canonical bank-quarter fact. Every financial value is a direct typed parse of source text.
CREATE TABLE core.bank_quarter_financials AS
SELECT
    cert_parsed AS cert,
    rssdid_parsed AS rssdid,
    NULLIF(TRIM(NAMEFULL), '') AS institution_name,
    reporting_date_parsed AS reporting_date,
    NULLIF(TRIM(STALP), '') AS state,
    NULLIF(TRIM(BKCLASS), '') AS bank_class,
    NULLIF(TRIM(REGAGNT), '') AS primary_regulator,
    CASE WHEN ACTIVE = '1' THEN TRUE WHEN ACTIVE = '0' THEN FALSE ELSE NULL END AS active_status,
    TRY_CAST(NULLIF(TRIM(ASSET), '') AS DECIMAL(38, 6)) AS asset,
    TRY_CAST(NULLIF(TRIM(EQ), '') AS DECIMAL(38, 6)) AS equity,
    TRY_CAST(NULLIF(TRIM(EQTOT), '') AS DECIMAL(38, 6)) AS total_equity,
    TRY_CAST(NULLIF(TRIM(LNLSGR), '') AS DECIMAL(38, 6)) AS gross_loans_leases,
    TRY_CAST(NULLIF(TRIM(LNLSNET), '') AS DECIMAL(38, 6)) AS net_loans_leases,
    TRY_CAST(NULLIF(TRIM(P3ASSET), '') AS DECIMAL(38, 6)) AS past_due_30_89,
    TRY_CAST(NULLIF(TRIM(P9ASSET), '') AS DECIMAL(38, 6)) AS past_due_90_plus,
    TRY_CAST(NULLIF(TRIM(NAASSET), '') AS DECIMAL(38, 6)) AS nonaccrual_assets,
    TRY_CAST(NULLIF(TRIM(ORE), '') AS DECIMAL(38, 6)) AS other_real_estate,
    TRY_CAST(NULLIF(TRIM(CHBAL), '') AS DECIMAL(38, 6)) AS cash_balances,
    TRY_CAST(NULLIF(TRIM(SC), '') AS DECIMAL(38, 6)) AS securities,
    TRY_CAST(NULLIF(TRIM(DEP), '') AS DECIMAL(38, 6)) AS deposits,
    TRY_CAST(NULLIF(TRIM(DEPDOM), '') AS DECIMAL(38, 6)) AS domestic_deposits,
    TRY_CAST(NULLIF(TRIM(DEPCSBQ), '') AS DECIMAL(38, 6)) AS assessable_deposits,
    TRY_CAST(NULLIF(TRIM(FREPO), '') AS DECIMAL(38, 6)) AS fed_funds_reverse_repos,
    TRY_CAST(NULLIF(TRIM(OTHBFHLB), '') AS DECIMAL(38, 6)) AS fhlb_advances,
    TRY_CAST(NULLIF(TRIM(LNRECONS), '') AS DECIMAL(38, 6)) AS construction_loans,
    TRY_CAST(NULLIF(TRIM(LNREMULT), '') AS DECIMAL(38, 6)) AS multifamily_loans,
    TRY_CAST(NULLIF(TRIM(LNRERES), '') AS DECIMAL(38, 6)) AS residential_loans,
    TRY_CAST(NULLIF(TRIM(LNCI), '') AS DECIMAL(38, 6)) AS commercial_industrial_loans,
    TRY_CAST(NULLIF(TRIM(LNCON), '') AS DECIMAL(38, 6)) AS consumer_loans,
    TRY_CAST(NULLIF(TRIM(LNCRCD), '') AS DECIMAL(38, 6)) AS credit_card_loans,
    TRY_CAST(NULLIF(TRIM(NIMQ), '') AS DECIMAL(38, 6)) AS quarterly_net_interest_income,
    TRY_CAST(NULLIF(TRIM(NIMYQ), '') AS DECIMAL(38, 6)) AS quarterly_net_interest_margin,
    TRY_CAST(NULLIF(TRIM(NETINCQ), '') AS DECIMAL(38, 6)) AS quarterly_net_income,
    TRY_CAST(NULLIF(TRIM(NONIIQ), '') AS DECIMAL(38, 6)) AS quarterly_noninterest_income,
    TRY_CAST(NULLIF(TRIM(NONIXQ), '') AS DECIMAL(38, 6)) AS quarterly_noninterest_expense,
    TRY_CAST(NULLIF(TRIM(PTAXNETINCQ), '') AS DECIMAL(38, 6)) AS quarterly_pretax_income,
    TRY_CAST(NULLIF(TRIM(ROAQ), '') AS DECIMAL(38, 6)) AS quarterly_return_on_assets,
    TRY_CAST(NULLIF(TRIM(EEFFQR), '') AS DECIMAL(38, 6)) AS quarterly_efficiency_ratio,
    TRY_CAST(NULLIF(TRIM(INTEXPYQ), '') AS DECIMAL(38, 6)) AS quarterly_funding_cost,
    TRY_CAST(NULLIF(TRIM(NTLNLSQ), '') AS DECIMAL(38, 6)) AS quarterly_net_chargeoffs,
    requested_quarter AS source_quarter,
    ingestion_run_id AS source_run_id,
    configuration_hash AS source_configuration_hash,
    quarter_raw_hash AS source_raw_hash,
    source_manifest_path,
    extraction_timestamp,
    downloader_version,
    normalization_version,
    validation_status,
    source_record_reference,
    '{{financial_source_path}}' AS source_file,
    '{{financial_source_hash}}' AS source_sha256,
    '{{build_run_id}}' AS build_run_id,
    '{{configuration_hash}}' AS build_configuration_hash,
    '009_build_bank_quarter_fact.sql' AS sql_version
FROM staging.financials;
